<?php

return [
    'categories' => [
        'Featured Products',
        'New Arrivals',
        'Festival Offers',
        'Kids Crackers',
        'Sparklers',
        'Flower Pots',
        'Ground Chakkars',
        'Bombs',
        'Rockets',
        'Gift Boxes',
        'Fancy Items',
        'Family Combo Packs',
    ],
    'products' => [
        [
            'id' => 1,
            'name' => '12 Shot Sky Fountain',
            'category' => 'Fancy Items',
            'price' => 450,
            'original_price' => 900,
            'discount' => '50%',
            'stock' => 10,
            'image_icon' => '🎆',
            'featured' => true,
        ],
        [
            'id' => 2,
            'name' => 'Electric Sparklers (15cm)',
            'category' => 'Sparklers',
            'price' => 120,
            'original_price' => 240,
            'discount' => '50%',
            'stock' => 50,
            'image_icon' => '✨',
            'featured' => true,
        ],
        [
            'id' => 3,
            'name' => 'Peacock Flower Pots',
            'category' => 'Flower Pots',
            'price' => 280,
            'original_price' => 560,
            'discount' => '50%',
            'stock' => 20,
            'image_icon' => '🌋',
            'featured' => true,
        ],
        [
            'id' => 4,
            'name' => 'Giant Ground Chakkar',
            'category' => 'Ground Chakkars',
            'price' => 150,
            'original_price' => 300,
            'discount' => '50%',
            'stock' => 35,
            'image_icon' => '🌀',
            'featured' => false,
        ],
        [
            'id' => 5,
            'name' => 'Classic Atom Bomb',
            'category' => 'Bombs',
            'price' => 180,
            'original_price' => 360,
            'discount' => '50%',
            'stock' => 0, // Out of stock example
            'image_icon' => '💣',
            'featured' => true,
        ],
        [
            'id' => 6,
            'name' => 'Magic Whip for Kids',
            'category' => 'Kids Crackers',
            'price' => 80,
            'original_price' => 160,
            'discount' => '50%',
            'stock' => 100,
            'image_icon' => '🪄',
            'featured' => false,
        ],
        [
            'id' => 7,
            'name' => 'Mega Rocket',
            'category' => 'Rockets',
            'price' => 220,
            'original_price' => 440,
            'discount' => '50%',
            'stock' => 15,
            'image_icon' => '🚀',
            'featured' => false,
        ],
    ],
    'combos' => [
        [
            'id' => 101,
            'name' => 'Mega Family Cracker Box',
            'category' => 'Family Combo Packs',
            'price' => 2499,
            'original_price' => 5000,
            'discount' => '50%',
            'stock' => 25,
            'image_icon' => '📦',
            'items_included' => 45,
            'featured' => true,
        ],
        [
            'id' => 102,
            'name' => 'Kids Special Combo',
            'category' => 'Family Combo Packs',
            'price' => 999,
            'original_price' => 2000,
            'discount' => '50%',
            'stock' => 40,
            'image_icon' => '🎁',
            'items_included' => 20,
            'featured' => false,
        ],
        [
            'id' => 103,
            'name' => 'Premium Festival Combo',
            'category' => 'Family Combo Packs',
            'price' => 4999,
            'original_price' => 10000,
            'discount' => '50%',
            'stock' => 10,
            'image_icon' => '🎊',
            'items_included' => 75,
            'featured' => true,
        ]
    ]
];
